version: '3'

services:

  run:
    container_name: local-althingi-aggregator-run
    labels:
      - althingi_service=aggregator
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=${ENV_ENVIRONMENT:-DEVELOPMENT}
      - CONSUMER_CACHE_TYPE=${ENV_CONSUMER_CACHE_TYPE:-none}
      - CONSUMER_CACHE_HOST=${ENV_CONSUMER_CACHE_HOST:-cache-consumer}
      - CONSUMER_CACHE_PORT=${ENV_CONSUMER_CACHE_PORT:-6379}

      - PROVIDER_CACHE_TYPE=${ENV_PROVIDER_CACHE_TYPE:-none}
      - PROVIDER_CACHE_HOST=${ENV_PROVIDER_CACHE_HOST:-cache-provider}
      - PROVIDER_CACHE_PORT=${ENV_PROVIDER_CACHE_PORT:-6379}

      - AGGREGATOR_CONSUMER_SCHEMA=${ENV_AGGREGATOR_CONSUMER_SCHEMA:-http}
      - AGGREGATOR_CONSUMER_HOST=${ENV_AGGREGATOR_CONSUMER_HOST:-host.docker.internal}
      - AGGREGATOR_CONSUMER_PORT=${ENV_AGGREGATOR_CONSUMER_PORT:-7070}

    volumes:
      - ./bin/:/var/app/bin
      - ./config/:/var/app/config
      - ./src/:/var/app/src
      - ./public/:/var/app/public
      - ./composer.json/:/var/app/composer.json
      - ./composer.lock/:/var/app/composer.lock

  test:
    container_name: local-althingi-aggregator-test
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    environment:
        - PROVIDER_CACHE_TYPE=none
        - CONSUMER_CACHE_TYPE=none
    volumes:
        - ./config/:/var/app/config
        - ./src/:/var/app/src
        - ./public/:/var/app/public
        - ./tests/:/var/app/tests
        - ./phpcs.xml/:/var/app/phpcs.xml
        - ./phpunit.xml.dist/:/var/app/phpunit.xml
        - ./composer.json/:/var/app/composer.json
        - ./composer.lock/:/var/app/composer.lock
    command: composer test && composer sniff"

  cache-consumer:
    container_name: local-althingi-aggregator-cache-concumer
    image: redis:4.0.11

  cache-provider:
    container_name: local-althingi-aggregator-cache-provider
    image: redis:4.0.11

networks:
    x-althingi:
        driver: bridge
