version: '3'

services:

  run:
    container_name: local-althingi-aggregator-run
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=${ENV_ENVIRONMENT:-DEVELOPMENT}
      - CONSUMER_CACHE_TYPE=${ENV_CONSUMER_CACHE_TYPE:-none}
      - CONSUMER_CACHE_HOST=${ENV_CONSUMER_CACHE_HOST:-cache-consumer}
      - CONSUMER_CACHE_PORT=${ENV_CONSUMER_CACHE_PORT:-6379}

      - PROVIDER_CACHE_TYPE=${ENV_PROVIDER_CACHE_TYPE:-none}
      - PROVIDER_CACHE_HOST=${ENV_PROVIDER_CACHE_HOST:-cache-provider}
      - PROVIDER_CACHE_PORT=${ENV_PROVIDER_CACHE_PORT:-6379}

      - AGGREGATOR_CONSUMER_SCHEMA=${ENV_AGGREGATOR_CONSUMER_SCHEMA:-http}
      - AGGREGATOR_CONSUMER_HOST=${ENV_AGGREGATOR_CONSUMER_HOST:-host.docker.internal}
      - AGGREGATOR_CONSUMER_PORT=${ENV_AGGREGATOR_CONSUMER_PORT:-8080}
    volumes:
      - ./bin/:/var/www/html/bin
      - ./config/:/var/www/html/config
      - ./src/:/var/www/html/src
      - ./public/:/var/www/html/public
      - ./vendor/:/var/www/html/vendor
      - ./composer.json/:/var/www/html/composer.json
      - ./composer.lock/:/var/www/html/composer.lock
    depends_on:
      - cache-consumer
      - cache-provider
      - echo-server

  test:
    container_name: local-althingi-aggregator-test
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    environment:
        - PROVIDER_CACHE_TYPE=none
        - CONSUMER_CACHE_TYPE=none
    volumes:
        - ./config/:/var/www/html/config
        - ./src/:/var/www/html/src
        - ./public/:/var/www/html/public
        - ./tests/:/var/www/html/tests
        - ./phpcs.xml/:/var/www/html/phpcs.xml
        - ./phpunit.xml.dist/:/var/www/html/phpunit.xml

        # - ./vendor/:/var/www/html/vendor
        # - ./composer.json/:/var/www/html/composer.json
        # - ./composer.lock/:/var/www/html/composer.lock

    working_dir: /var/www/html
    command: bash -c "./vendor/bin/phpunit && ./vendor/bin/phpcs --standard=./phpcs.xml ./src"
    # command: bash -c "./vendor/bin/phpunit --coverage-html ./tests/doc && ./vendor/bin/phpcs --standard=./phpcs.xml ./src"

  cache-consumer:
    container_name: local-althingi-aggregator-cache-concumer
    image: redis:4.0.11

  cache-provider:
    container_name: local-althingi-aggregator-cache-provider
    image: redis:4.0.11

  echo-server:
    image:  mendhak/http-https-echo:17
    container_name: echo-server
    environment:
      - HTTP_PORT=8080
